export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST";
export const REMOVE_FROM_WISHLIST = "REMOVE_FROM_WISHLIST";
export const PRODUCT_LOADED = "PRODUCT_LOADED";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const UPDATE_PRODUCT = "ADD_PRODUCT";
export const DELETE_PRODUCT = "REMOVE_PRODUCT";

// Filter
export const KEYWORD = 'KEYWORD'
export const TOGGLE_BRAND = 'TOGGLE_BRAND'
export const TOGGLE_STOCK = 'STOCK'
export const CLEAR_FILTER = 'CLEAR_FILTER'